#!/bin/zsh

# Function to source files if they exist
function zsh_add_file() {
    [ -f "$ZDOTDIR/$1" ] && source "$ZDOTDIR/$1"
}

function parse_git_branch() {
    branch=`git branch --show-current 2> /dev/null`
    if [ ! "${branch}" = "" ]; then
        echo " [${branch}]"
    else
        echo ""
    fi
}

function watch () {
    while :;
    do
      a=$($@);
      clear;
      echo -e "$(date)\n$a";
      sleep 1;
    done
}

function random () {
    head /dev/urandom | base64 | tr -dc 'a-zA-Z0-9' | fold -w $1 | head -n 1
}